// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  ApiGetHealthHealthCheckData,
  ApiGetHealthHealthCheckResponses,
  ApiGetMetricsMetricsData,
  ApiGetMetricsMetricsResponses,
  ApiGetRootRootData,
  ApiGetRootRootResponses,
  AuthPostApiV1AuthLoginLoginData,
  AuthPostApiV1AuthLoginLoginResponses,
  AuthPostApiV1AuthLoginLoginErrors,
  AuthPostApiV1AuthLoginJsonLoginJsonData,
  AuthPostApiV1AuthLoginJsonLoginJsonResponses,
  AuthPostApiV1AuthLoginJsonLoginJsonErrors,
  AuthGetApiV1AuthMeGetCurrentUserProfileData,
  AuthGetApiV1AuthMeGetCurrentUserProfileResponses,
  AuthPostApiV1AuthLogoutLogoutData,
  AuthPostApiV1AuthLogoutLogoutResponses,
  AuthPostApiV1AuthTokenOauthTokenData,
  AuthPostApiV1AuthTokenOauthTokenResponses,
  AuthPostApiV1AuthTokenOauthTokenErrors,
  AuthGetApiV1AuthAdminUsersListUsersData,
  AuthGetApiV1AuthAdminUsersListUsersResponses,
  AuthPostApiV1AuthAdminUsersCreateUserData,
  AuthPostApiV1AuthAdminUsersCreateUserResponses,
  AuthPostApiV1AuthAdminUsersCreateUserErrors,
  AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserData,
  AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserResponses,
  AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserErrors,
  AuthGetApiV1AuthAdminUsersUserIdGetUserData,
  AuthGetApiV1AuthAdminUsersUserIdGetUserResponses,
  AuthGetApiV1AuthAdminUsersUserIdGetUserErrors,
  AuthPutApiV1AuthAdminUsersUserIdUpdateUserData,
  AuthPutApiV1AuthAdminUsersUserIdUpdateUserResponses,
  AuthPutApiV1AuthAdminUsersUserIdUpdateUserErrors,
  AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserData,
  AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserResponses,
  AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserErrors,
  AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserData,
  AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserResponses,
  AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserErrors,
  AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordData,
  AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordResponses,
  AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordErrors,
  AuthPostApiV1AuthOauth2ClientsCreateOauthClientData,
  AuthPostApiV1AuthOauth2ClientsCreateOauthClientResponses,
  AuthPostApiV1AuthOauth2ClientsCreateOauthClientErrors,
  AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientData,
  AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientResponses,
  AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientErrors,
  AuthGetApiV1AuthOauth2AuthorizeOauthAuthorizeData,
  AuthGetApiV1AuthOauth2AuthorizeOauthAuthorizeResponses,
  NinPostApiV1NinVerifyVerifyNinData,
  NinPostApiV1NinVerifyVerifyNinResponses,
  NinPostApiV1NinVerifyVerifyNinErrors,
  NinGetApiV1NinStatusNinGetNinStatusData,
  NinGetApiV1NinStatusNinGetNinStatusResponses,
  NinGetApiV1NinStatusNinGetNinStatusErrors,
  NinPostApiV1NinLookupLookupNinData,
  NinPostApiV1NinLookupLookupNinResponses,
  NinPostApiV1NinLookupLookupNinErrors,
  BvnPostApiV1BvnVerifyVerifyBvnData,
  BvnPostApiV1BvnVerifyVerifyBvnResponses,
  BvnPostApiV1BvnVerifyVerifyBvnErrors,
  BvnGetApiV1BvnStatusBvnGetBvnStatusData,
  BvnGetApiV1BvnStatusBvnGetBvnStatusResponses,
  BvnGetApiV1BvnStatusBvnGetBvnStatusErrors,
  BvnPostApiV1BvnLookupLookupBvnData,
  BvnPostApiV1BvnLookupLookupBvnResponses,
  BvnPostApiV1BvnLookupLookupBvnErrors,
  BvnPostApiV1BvnMatchMatchBvnData,
  BvnPostApiV1BvnMatchMatchBvnResponses,
  BvnPostApiV1BvnMatchMatchBvnErrors,
  BvnGetApiV1BvnBanksGetSupportedBanksData,
  BvnGetApiV1BvnBanksGetSupportedBanksResponses,
  SmsPostApiV1SmsSendSendSmsData,
  SmsPostApiV1SmsSendSendSmsResponses,
  SmsPostApiV1SmsSendSendSmsErrors,
  SmsPostApiV1SmsBulkSendBulkSmsData,
  SmsPostApiV1SmsBulkSendBulkSmsResponses,
  SmsPostApiV1SmsBulkSendBulkSmsErrors,
  SmsPostApiV1SmsOtpGenerateGenerateOtpData,
  SmsPostApiV1SmsOtpGenerateGenerateOtpResponses,
  SmsPostApiV1SmsOtpGenerateGenerateOtpErrors,
  SmsPostApiV1SmsOtpVerifyVerifyOtpData,
  SmsPostApiV1SmsOtpVerifyVerifyOtpResponses,
  SmsPostApiV1SmsOtpVerifyVerifyOtpErrors,
  SmsGetApiV1SmsStatusMessageIdGetMessageStatusData,
  SmsGetApiV1SmsStatusMessageIdGetMessageStatusResponses,
  SmsGetApiV1SmsStatusMessageIdGetMessageStatusErrors,
  SmsGetApiV1SmsBalanceGetSmsBalanceData,
  SmsGetApiV1SmsBalanceGetSmsBalanceResponses,
  SmsGetApiV1SmsTemplatesGetMessageTemplatesData,
  SmsGetApiV1SmsTemplatesGetMessageTemplatesResponses,
  AiPostApiV1AiChatChatCompletionData,
  AiPostApiV1AiChatChatCompletionResponses,
  AiPostApiV1AiChatChatCompletionErrors,
  AiPostApiV1AiGenerateGenerateContentData,
  AiPostApiV1AiGenerateGenerateContentResponses,
  AiPostApiV1AiGenerateGenerateContentErrors,
  AiPostApiV1AiAnalyzeAnalyzeTextData,
  AiPostApiV1AiAnalyzeAnalyzeTextResponses,
  AiPostApiV1AiAnalyzeAnalyzeTextErrors,
  AiPostApiV1AiTranslateTranslateTextData,
  AiPostApiV1AiTranslateTranslateTextResponses,
  AiPostApiV1AiTranslateTranslateTextErrors,
  AiGetApiV1AiModelsGetAvailableModelsData,
  AiGetApiV1AiModelsGetAvailableModelsResponses,
  AiGetApiV1AiConversationsConversationIdGetConversationData,
  AiGetApiV1AiConversationsConversationIdGetConversationResponses,
  AiGetApiV1AiConversationsConversationIdGetConversationErrors,
  AiGetApiV1AiUsageGetUsageStatisticsData,
  AiGetApiV1AiUsageGetUsageStatisticsResponses,
  HealthGetApiV1ServicesHealthGetServicesHealthData,
  HealthGetApiV1ServicesHealthGetServicesHealthResponses,
  HealthGetApiV1DpiHealthGetDpiHealthData,
  HealthGetApiV1DpiHealthGetDpiHealthResponses,
  HealthGetApiV1ServicesServiceNameHealthGetServiceHealthData,
  HealthGetApiV1ServicesServiceNameHealthGetServiceHealthResponses,
  HealthGetApiV1ServicesServiceNameHealthGetServiceHealthErrors,
  HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsData,
  HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsResponses,
  HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsErrors,
  ExamplesGetApiV1ExamplesNinNinExamplesData,
  ExamplesGetApiV1ExamplesNinNinExamplesResponses,
  ExamplesGetApiV1ExamplesSmsSmsExamplesData,
  ExamplesGetApiV1ExamplesSmsSmsExamplesResponses,
  ExamplesGetApiV1ExamplesAuthAuthExamplesData,
  ExamplesGetApiV1ExamplesAuthAuthExamplesResponses,
  ExamplesGetApiV1ExamplesIntegrationIntegrationExamplesData,
  ExamplesGetApiV1ExamplesIntegrationIntegrationExamplesResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 * Health check endpoint.
 */
export const apiGetHealthHealthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<ApiGetHealthHealthCheckData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ApiGetHealthHealthCheckResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/health",
    ...options,
  });
};

/**
 * Metrics
 * Prometheus metrics endpoint.
 */
export const apiGetMetricsMetrics = <ThrowOnError extends boolean = false>(
  options?: Options<ApiGetMetricsMetricsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ApiGetMetricsMetricsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/metrics",
    ...options,
  });
};

/**
 * Root
 * Root endpoint.
 */
export const apiGetRootRoot = <ThrowOnError extends boolean = false>(
  options?: Options<ApiGetRootRootData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ApiGetRootRootResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/",
    ...options,
  });
};

/**
 * Login
 * 🔐 OAuth2 Compatible Login
 */
export const authPostApiV1AuthLoginLogin = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthPostApiV1AuthLoginLoginData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthPostApiV1AuthLoginLoginResponses,
    AuthPostApiV1AuthLoginLoginErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Login Json
 * 🚀 JSON Login for Nigerian Startups
 */
export const authPostApiV1AuthLoginJsonLoginJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthPostApiV1AuthLoginJsonLoginJsonData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthPostApiV1AuthLoginJsonLoginJsonResponses,
    AuthPostApiV1AuthLoginJsonLoginJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/login/json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Current User Profile
 * 👤 Get Current User Profile
 */
export const authGetApiV1AuthMeGetCurrentUserProfile = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthGetApiV1AuthMeGetCurrentUserProfileData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthGetApiV1AuthMeGetCurrentUserProfileResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/me",
    ...options,
  });
};

/**
 * Logout
 * 🚪 User Logout
 */
export const authPostApiV1AuthLogoutLogout = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthPostApiV1AuthLogoutLogoutData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    AuthPostApiV1AuthLogoutLogoutResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/logout",
    ...options,
  });
};

/**
 * Oauth Token
 * 🔑 OAuth2 Token Endpoint
 */
export const authPostApiV1AuthTokenOauthToken = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthPostApiV1AuthTokenOauthTokenData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthPostApiV1AuthTokenOauthTokenResponses,
    AuthPostApiV1AuthTokenOauthTokenErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Users
 * 📋 List All Users (Admin Only)
 */
export const authGetApiV1AuthAdminUsersListUsers = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthGetApiV1AuthAdminUsersListUsersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthGetApiV1AuthAdminUsersListUsersResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/admin/users",
    ...options,
  });
};

/**
 * Create User
 * 👥 Create User Account (Admin Only)
 */
export const authPostApiV1AuthAdminUsersCreateUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthPostApiV1AuthAdminUsersCreateUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthPostApiV1AuthAdminUsersCreateUserResponses,
    AuthPostApiV1AuthAdminUsersCreateUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/admin/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete User
 * 🗑️ Delete User (Admin Only)
 */
export const authDeleteApiV1AuthAdminUsersUserIdDeleteUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserResponses,
    AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/admin/users/{user_id}",
    ...options,
  });
};

/**
 * Get User
 * 👤 Get User by ID (Admin Only)
 */
export const authGetApiV1AuthAdminUsersUserIdGetUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthGetApiV1AuthAdminUsersUserIdGetUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    AuthGetApiV1AuthAdminUsersUserIdGetUserResponses,
    AuthGetApiV1AuthAdminUsersUserIdGetUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/admin/users/{user_id}",
    ...options,
  });
};

/**
 * Update User
 * ✏️ Update User (Admin Only)
 */
export const authPutApiV1AuthAdminUsersUserIdUpdateUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthPutApiV1AuthAdminUsersUserIdUpdateUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    AuthPutApiV1AuthAdminUsersUserIdUpdateUserResponses,
    AuthPutApiV1AuthAdminUsersUserIdUpdateUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/admin/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Activate User
 * ✅ Activate User Account (Admin Only)
 */
export const authPostApiV1AuthAdminUsersUserIdActivateActivateUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserResponses,
    AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/admin/users/{user_id}/activate",
    ...options,
  });
};

/**
 * Deactivate User
 * ❌ Deactivate User Account (Admin Only)
 */
export const authPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserResponses,
    AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/admin/users/{user_id}/deactivate",
    ...options,
  });
};

/**
 * Reset User Password
 * 🔑 Reset User Password (Admin Only)
 */
export const authPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordResponses,
    AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/admin/users/{user_id}/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Create Oauth Client
 * 🔗 Create OAuth2 Client
 */
export const authPostApiV1AuthOauth2ClientsCreateOauthClient = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AuthPostApiV1AuthOauth2ClientsCreateOauthClientData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    AuthPostApiV1AuthOauth2ClientsCreateOauthClientResponses,
    AuthPostApiV1AuthOauth2ClientsCreateOauthClientErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/oauth2/clients",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Oauth Client
 * 🔍 Get OAuth2 Client
 */
export const authGetApiV1AuthOauth2ClientsClientIdGetOauthClient = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientResponses,
    AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/oauth2/clients/{client_id}",
    ...options,
  });
};

/**
 * Oauth Authorize
 * 🔐 OAuth2 Authorization Endpoint
 */
export const authGetApiV1AuthOauth2AuthorizeOauthAuthorize = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    AuthGetApiV1AuthOauth2AuthorizeOauthAuthorizeData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthGetApiV1AuthOauth2AuthorizeOauthAuthorizeResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/oauth2/authorize",
    ...options,
  });
};

/**
 * Verify Nin
 * 🇳🇬 Verify Nigerian Identity Number (NIN)
 */
export const ninPostApiV1NinVerifyVerifyNin = <
  ThrowOnError extends boolean = false,
>(
  options: Options<NinPostApiV1NinVerifyVerifyNinData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    NinPostApiV1NinVerifyVerifyNinResponses,
    NinPostApiV1NinVerifyVerifyNinErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/nin/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Nin Status
 * 📊 Get NIN Verification Status
 */
export const ninGetApiV1NinStatusNinGetNinStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<NinGetApiV1NinStatusNinGetNinStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    NinGetApiV1NinStatusNinGetNinStatusResponses,
    NinGetApiV1NinStatusNinGetNinStatusErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/nin/status/{nin}",
    ...options,
  });
};

/**
 * Lookup Nin
 * 🔍 Basic NIN Lookup
 */
export const ninPostApiV1NinLookupLookupNin = <
  ThrowOnError extends boolean = false,
>(
  options: Options<NinPostApiV1NinLookupLookupNinData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    NinPostApiV1NinLookupLookupNinResponses,
    NinPostApiV1NinLookupLookupNinErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/nin/lookup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify Bvn
 * 🇳🇬 Verify Bank Verification Number (BVN)
 */
export const bvnPostApiV1BvnVerifyVerifyBvn = <
  ThrowOnError extends boolean = false,
>(
  options: Options<BvnPostApiV1BvnVerifyVerifyBvnData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    BvnPostApiV1BvnVerifyVerifyBvnResponses,
    BvnPostApiV1BvnVerifyVerifyBvnErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/bvn/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Bvn Status
 * 📊 Get BVN Verification Status
 */
export const bvnGetApiV1BvnStatusBvnGetBvnStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<BvnGetApiV1BvnStatusBvnGetBvnStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    BvnGetApiV1BvnStatusBvnGetBvnStatusResponses,
    BvnGetApiV1BvnStatusBvnGetBvnStatusErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/bvn/status/{bvn}",
    ...options,
  });
};

/**
 * Lookup Bvn
 * 🔍 Basic BVN Lookup
 */
export const bvnPostApiV1BvnLookupLookupBvn = <
  ThrowOnError extends boolean = false,
>(
  options: Options<BvnPostApiV1BvnLookupLookupBvnData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    BvnPostApiV1BvnLookupLookupBvnResponses,
    BvnPostApiV1BvnLookupLookupBvnErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/bvn/lookup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Match Bvn
 * 🔗 Match BVN with User Data
 */
export const bvnPostApiV1BvnMatchMatchBvn = <
  ThrowOnError extends boolean = false,
>(
  options: Options<BvnPostApiV1BvnMatchMatchBvnData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    BvnPostApiV1BvnMatchMatchBvnResponses,
    BvnPostApiV1BvnMatchMatchBvnErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/bvn/match",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Supported Banks
 * 🏦 Get Supported Nigerian Banks
 */
export const bvnGetApiV1BvnBanksGetSupportedBanks = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<BvnGetApiV1BvnBanksGetSupportedBanksData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    BvnGetApiV1BvnBanksGetSupportedBanksResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/bvn/banks",
    ...options,
  });
};

/**
 * Send Sms
 * 📱 Send SMS to Nigerian Number
 */
export const smsPostApiV1SmsSendSendSms = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SmsPostApiV1SmsSendSendSmsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    SmsPostApiV1SmsSendSendSmsResponses,
    SmsPostApiV1SmsSendSendSmsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/sms/send",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Send Bulk Sms
 * 📤 Send Bulk SMS Messages
 */
export const smsPostApiV1SmsBulkSendBulkSms = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SmsPostApiV1SmsBulkSendBulkSmsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    SmsPostApiV1SmsBulkSendBulkSmsResponses,
    SmsPostApiV1SmsBulkSendBulkSmsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/sms/bulk",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Generate Otp
 * 🔐 Generate and Send OTP
 */
export const smsPostApiV1SmsOtpGenerateGenerateOtp = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SmsPostApiV1SmsOtpGenerateGenerateOtpData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    SmsPostApiV1SmsOtpGenerateGenerateOtpResponses,
    SmsPostApiV1SmsOtpGenerateGenerateOtpErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/sms/otp/generate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify Otp
 * ✅ Verify OTP Code
 */
export const smsPostApiV1SmsOtpVerifyVerifyOtp = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SmsPostApiV1SmsOtpVerifyVerifyOtpData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    SmsPostApiV1SmsOtpVerifyVerifyOtpResponses,
    SmsPostApiV1SmsOtpVerifyVerifyOtpErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/sms/otp/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Message Status
 * 📊 Check Message Delivery Status
 */
export const smsGetApiV1SmsStatusMessageIdGetMessageStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SmsGetApiV1SmsStatusMessageIdGetMessageStatusData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    SmsGetApiV1SmsStatusMessageIdGetMessageStatusResponses,
    SmsGetApiV1SmsStatusMessageIdGetMessageStatusErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/sms/status/{message_id}",
    ...options,
  });
};

/**
 * Get Sms Balance
 * 💰 Check SMS Credit Balance
 */
export const smsGetApiV1SmsBalanceGetSmsBalance = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SmsGetApiV1SmsBalanceGetSmsBalanceData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    SmsGetApiV1SmsBalanceGetSmsBalanceResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/sms/balance",
    ...options,
  });
};

/**
 * Get Message Templates
 * 📝 Get Message Templates
 */
export const smsGetApiV1SmsTemplatesGetMessageTemplates = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SmsGetApiV1SmsTemplatesGetMessageTemplatesData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    SmsGetApiV1SmsTemplatesGetMessageTemplatesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/sms/templates",
    ...options,
  });
};

/**
 * Chat Completion
 * 🤖 Interactive Chat Completion
 */
export const aiPostApiV1AiChatChatCompletion = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiPostApiV1AiChatChatCompletionData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AiPostApiV1AiChatChatCompletionResponses,
    AiPostApiV1AiChatChatCompletionErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/ai/chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Generate Content
 * 📝 Generate Content
 */
export const aiPostApiV1AiGenerateGenerateContent = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiPostApiV1AiGenerateGenerateContentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AiPostApiV1AiGenerateGenerateContentResponses,
    AiPostApiV1AiGenerateGenerateContentErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/ai/generate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Analyze Text
 * 🔍 Analyze Text Content
 */
export const aiPostApiV1AiAnalyzeAnalyzeText = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiPostApiV1AiAnalyzeAnalyzeTextData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AiPostApiV1AiAnalyzeAnalyzeTextResponses,
    AiPostApiV1AiAnalyzeAnalyzeTextErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/ai/analyze",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Translate Text
 * 🌍 Nigerian Language Translation
 */
export const aiPostApiV1AiTranslateTranslateText = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AiPostApiV1AiTranslateTranslateTextData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AiPostApiV1AiTranslateTranslateTextResponses,
    AiPostApiV1AiTranslateTranslateTextErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/ai/translate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Available Models
 * 🧠 Get Available AI Models
 */
export const aiGetApiV1AiModelsGetAvailableModels = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AiGetApiV1AiModelsGetAvailableModelsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AiGetApiV1AiModelsGetAvailableModelsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/ai/models",
    ...options,
  });
};

/**
 * Get Conversation
 * 💬 Get Conversation History
 */
export const aiGetApiV1AiConversationsConversationIdGetConversation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AiGetApiV1AiConversationsConversationIdGetConversationData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    AiGetApiV1AiConversationsConversationIdGetConversationResponses,
    AiGetApiV1AiConversationsConversationIdGetConversationErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/ai/conversations/{conversation_id}",
    ...options,
  });
};

/**
 * Get Usage Statistics
 * 📊 Get Token Usage Statistics
 */
export const aiGetApiV1AiUsageGetUsageStatistics = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AiGetApiV1AiUsageGetUsageStatisticsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AiGetApiV1AiUsageGetUsageStatisticsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/ai/usage",
    ...options,
  });
};

/**
 * Get Services Health
 * 💚 Platform Health Overview
 *
 * Comprehensive health check for all backend services.
 * Essential for monitoring Nigerian DPI platform status.
 */
export const healthGetApiV1ServicesHealthGetServicesHealth = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    HealthGetApiV1ServicesHealthGetServicesHealthData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    HealthGetApiV1ServicesHealthGetServicesHealthResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/services/health",
    ...options,
  });
};

/**
 * Get Dpi Health
 * 🇳🇬 Nigerian DPI Services Health
 *
 * Focused health check for core DPI services.
 * Tailored for Nigerian startup developers.
 */
export const healthGetApiV1DpiHealthGetDpiHealth = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<HealthGetApiV1DpiHealthGetDpiHealthData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    HealthGetApiV1DpiHealthGetDpiHealthResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/dpi/health",
    ...options,
  });
};

/**
 * Get Service Health
 * 🔍 Individual Service Health
 *
 * Detailed health check for a specific service.
 * Essential for troubleshooting and monitoring.
 */
export const healthGetApiV1ServicesServiceNameHealthGetServiceHealth = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    HealthGetApiV1ServicesServiceNameHealthGetServiceHealthData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    HealthGetApiV1ServicesServiceNameHealthGetServiceHealthResponses,
    HealthGetApiV1ServicesServiceNameHealthGetServiceHealthErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/services/{service_name}/health",
    ...options,
  });
};

/**
 * Get Service Metrics
 * 📈 Service Performance Metrics
 *
 * Detailed performance and usage metrics for specific service.
 * Critical for capacity planning and optimization.
 */
export const healthGetApiV1ServicesServiceNameMetricsGetServiceMetrics = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsResponses,
    HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/services/{service_name}/metrics",
    ...options,
  });
};

/**
 * Nin Examples
 * 📋 NIN Verification Examples
 */
export const examplesGetApiV1ExamplesNinNinExamples = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ExamplesGetApiV1ExamplesNinNinExamplesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ExamplesGetApiV1ExamplesNinNinExamplesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/examples/nin",
    ...options,
  });
};

/**
 * Sms Examples
 * 📱 Nigerian SMS Examples
 */
export const examplesGetApiV1ExamplesSmsSmsExamples = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ExamplesGetApiV1ExamplesSmsSmsExamplesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ExamplesGetApiV1ExamplesSmsSmsExamplesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/examples/sms",
    ...options,
  });
};

/**
 * Auth Examples
 * 🔐 OAuth2 Bearer Token Examples
 */
export const examplesGetApiV1ExamplesAuthAuthExamples = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ExamplesGetApiV1ExamplesAuthAuthExamplesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ExamplesGetApiV1ExamplesAuthAuthExamplesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/examples/auth",
    ...options,
  });
};

/**
 * Integration Examples
 * 🚀 Complete DPI Integration Examples
 */
export const examplesGetApiV1ExamplesIntegrationIntegrationExamples = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ExamplesGetApiV1ExamplesIntegrationIntegrationExamplesData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    ExamplesGetApiV1ExamplesIntegrationIntegrationExamplesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/examples/integration",
    ...options,
  });
};
