// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MetricsMetricsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/metrics";
};

export type MetricsMetricsGetResponses = {
  /**
   * Successful Response
   */
  200: string;
};

export type MetricsMetricsGetResponse =
  MetricsMetricsGetResponses[keyof MetricsMetricsGetResponses];

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyAuthServiceApiV1AuthPathOptionsData = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/auth/{path}";
};

export type ProxyAuthServiceApiV1AuthPathOptionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyAuthServiceApiV1AuthPathOptionsError =
  ProxyAuthServiceApiV1AuthPathOptionsErrors[keyof ProxyAuthServiceApiV1AuthPathOptionsErrors];

export type ProxyAuthServiceApiV1AuthPathOptionsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyAuthServiceApiV1AuthPathOptions2Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/auth/{path}";
};

export type ProxyAuthServiceApiV1AuthPathOptions2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyAuthServiceApiV1AuthPathOptions2Error =
  ProxyAuthServiceApiV1AuthPathOptions2Errors[keyof ProxyAuthServiceApiV1AuthPathOptions2Errors];

export type ProxyAuthServiceApiV1AuthPathOptions2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyAuthServiceApiV1AuthPathOptions3Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/auth/{path}";
};

export type ProxyAuthServiceApiV1AuthPathOptions3Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyAuthServiceApiV1AuthPathOptions3Error =
  ProxyAuthServiceApiV1AuthPathOptions3Errors[keyof ProxyAuthServiceApiV1AuthPathOptions3Errors];

export type ProxyAuthServiceApiV1AuthPathOptions3Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyAuthServiceApiV1AuthPathOptions4Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/auth/{path}";
};

export type ProxyAuthServiceApiV1AuthPathOptions4Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyAuthServiceApiV1AuthPathOptions4Error =
  ProxyAuthServiceApiV1AuthPathOptions4Errors[keyof ProxyAuthServiceApiV1AuthPathOptions4Errors];

export type ProxyAuthServiceApiV1AuthPathOptions4Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyAuthServiceApiV1AuthPathOptions5Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/auth/{path}";
};

export type ProxyAuthServiceApiV1AuthPathOptions5Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyAuthServiceApiV1AuthPathOptions5Error =
  ProxyAuthServiceApiV1AuthPathOptions5Errors[keyof ProxyAuthServiceApiV1AuthPathOptions5Errors];

export type ProxyAuthServiceApiV1AuthPathOptions5Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyAuthServiceApiV1AuthPathOptions6Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/auth/{path}";
};

export type ProxyAuthServiceApiV1AuthPathOptions6Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyAuthServiceApiV1AuthPathOptions6Error =
  ProxyAuthServiceApiV1AuthPathOptions6Errors[keyof ProxyAuthServiceApiV1AuthPathOptions6Errors];

export type ProxyAuthServiceApiV1AuthPathOptions6Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxySmsServiceApiV1SmsPathOptionsData = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/sms/{path}";
};

export type ProxySmsServiceApiV1SmsPathOptionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxySmsServiceApiV1SmsPathOptionsError =
  ProxySmsServiceApiV1SmsPathOptionsErrors[keyof ProxySmsServiceApiV1SmsPathOptionsErrors];

export type ProxySmsServiceApiV1SmsPathOptionsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxySmsServiceApiV1SmsPathOptions2Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/sms/{path}";
};

export type ProxySmsServiceApiV1SmsPathOptions2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxySmsServiceApiV1SmsPathOptions2Error =
  ProxySmsServiceApiV1SmsPathOptions2Errors[keyof ProxySmsServiceApiV1SmsPathOptions2Errors];

export type ProxySmsServiceApiV1SmsPathOptions2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxySmsServiceApiV1SmsPathOptions3Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/sms/{path}";
};

export type ProxySmsServiceApiV1SmsPathOptions3Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxySmsServiceApiV1SmsPathOptions3Error =
  ProxySmsServiceApiV1SmsPathOptions3Errors[keyof ProxySmsServiceApiV1SmsPathOptions3Errors];

export type ProxySmsServiceApiV1SmsPathOptions3Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxySmsServiceApiV1SmsPathOptions4Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/sms/{path}";
};

export type ProxySmsServiceApiV1SmsPathOptions4Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxySmsServiceApiV1SmsPathOptions4Error =
  ProxySmsServiceApiV1SmsPathOptions4Errors[keyof ProxySmsServiceApiV1SmsPathOptions4Errors];

export type ProxySmsServiceApiV1SmsPathOptions4Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxySmsServiceApiV1SmsPathOptions5Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/sms/{path}";
};

export type ProxySmsServiceApiV1SmsPathOptions5Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxySmsServiceApiV1SmsPathOptions5Error =
  ProxySmsServiceApiV1SmsPathOptions5Errors[keyof ProxySmsServiceApiV1SmsPathOptions5Errors];

export type ProxySmsServiceApiV1SmsPathOptions5Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxySmsServiceApiV1SmsPathOptions6Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/sms/{path}";
};

export type ProxySmsServiceApiV1SmsPathOptions6Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxySmsServiceApiV1SmsPathOptions6Error =
  ProxySmsServiceApiV1SmsPathOptions6Errors[keyof ProxySmsServiceApiV1SmsPathOptions6Errors];

export type ProxySmsServiceApiV1SmsPathOptions6Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyLlmServiceApiV1LlmPathOptionsData = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/llm/{path}";
};

export type ProxyLlmServiceApiV1LlmPathOptionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyLlmServiceApiV1LlmPathOptionsError =
  ProxyLlmServiceApiV1LlmPathOptionsErrors[keyof ProxyLlmServiceApiV1LlmPathOptionsErrors];

export type ProxyLlmServiceApiV1LlmPathOptionsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyLlmServiceApiV1LlmPathOptions2Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/llm/{path}";
};

export type ProxyLlmServiceApiV1LlmPathOptions2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyLlmServiceApiV1LlmPathOptions2Error =
  ProxyLlmServiceApiV1LlmPathOptions2Errors[keyof ProxyLlmServiceApiV1LlmPathOptions2Errors];

export type ProxyLlmServiceApiV1LlmPathOptions2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyLlmServiceApiV1LlmPathOptions3Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/llm/{path}";
};

export type ProxyLlmServiceApiV1LlmPathOptions3Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyLlmServiceApiV1LlmPathOptions3Error =
  ProxyLlmServiceApiV1LlmPathOptions3Errors[keyof ProxyLlmServiceApiV1LlmPathOptions3Errors];

export type ProxyLlmServiceApiV1LlmPathOptions3Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyLlmServiceApiV1LlmPathOptions4Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/llm/{path}";
};

export type ProxyLlmServiceApiV1LlmPathOptions4Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyLlmServiceApiV1LlmPathOptions4Error =
  ProxyLlmServiceApiV1LlmPathOptions4Errors[keyof ProxyLlmServiceApiV1LlmPathOptions4Errors];

export type ProxyLlmServiceApiV1LlmPathOptions4Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyLlmServiceApiV1LlmPathOptions5Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/llm/{path}";
};

export type ProxyLlmServiceApiV1LlmPathOptions5Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyLlmServiceApiV1LlmPathOptions5Error =
  ProxyLlmServiceApiV1LlmPathOptions5Errors[keyof ProxyLlmServiceApiV1LlmPathOptions5Errors];

export type ProxyLlmServiceApiV1LlmPathOptions5Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProxyLlmServiceApiV1LlmPathOptions6Data = {
  body?: never;
  path: {
    /**
     * Path
     */
    path: string;
  };
  query?: never;
  url: "/api/v1/llm/{path}";
};

export type ProxyLlmServiceApiV1LlmPathOptions6Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProxyLlmServiceApiV1LlmPathOptions6Error =
  ProxyLlmServiceApiV1LlmPathOptions6Errors[keyof ProxyLlmServiceApiV1LlmPathOptions6Errors];

export type ProxyLlmServiceApiV1LlmPathOptions6Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetServicesHealthApiV1ServicesHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/services/health";
};

export type GetServicesHealthApiV1ServicesHealthGetResponses = {
  /**
   * Response Get Services Health Api V1 Services Health Get
   * Successful Response
   */
  200: unknown;
};

export type GetServicesStatusApiV1ServicesStatusGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/services/status";
};

export type GetServicesStatusApiV1ServicesStatusGetResponses = {
  /**
   * Response Get Services Status Api V1 Services Status Get
   * Successful Response
   */
  200: unknown;
};

export type GetServiceHealthApiV1ServicesServiceNameHealthGetData = {
  body?: never;
  path: {
    /**
     * Service Name
     */
    service_name: string;
  };
  query?: never;
  url: "/api/v1/services/{service_name}/health";
};

export type GetServiceHealthApiV1ServicesServiceNameHealthGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetServiceHealthApiV1ServicesServiceNameHealthGetError =
  GetServiceHealthApiV1ServicesServiceNameHealthGetErrors[keyof GetServiceHealthApiV1ServicesServiceNameHealthGetErrors];

export type GetServiceHealthApiV1ServicesServiceNameHealthGetResponses = {
  /**
   * Response Get Service Health Api V1 Services  Service Name  Health Get
   * Successful Response
   */
  200: unknown;
};

export type GetServiceMetricsApiV1ServicesServiceNameMetricsGetData = {
  body?: never;
  path: {
    /**
     * Service Name
     */
    service_name: string;
  };
  query?: never;
  url: "/api/v1/services/{service_name}/metrics";
};

export type GetServiceMetricsApiV1ServicesServiceNameMetricsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetServiceMetricsApiV1ServicesServiceNameMetricsGetError =
  GetServiceMetricsApiV1ServicesServiceNameMetricsGetErrors[keyof GetServiceMetricsApiV1ServicesServiceNameMetricsGetErrors];

export type GetServiceMetricsApiV1ServicesServiceNameMetricsGetResponses = {
  /**
   * Response Get Service Metrics Api V1 Services  Service Name  Metrics Get
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};
