// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_get_token_api_v1_oauth2_token_post
 */
export type BodyGetTokenApiV1Oauth2TokenPost = {
  /**
   * Grant Type
   */
  grant_type: string;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Client Secret
   */
  client_secret?: string | null;
  /**
   * Code
   */
  code?: string | null;
  /**
   * Redirect Uri
   */
  redirect_uri?: string | null;
  /**
   * Refresh Token
   */
  refresh_token?: string | null;
};

/**
 * Body_login_user_api_v1_auth_login_post
 */
export type BodyLoginUserApiV1AuthLoginPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * NINBVNVerificationRequest
 */
export type NinbvnVerificationRequest = {
  /**
   * Nin
   */
  nin?: string | null;
  /**
   * Bvn
   */
  bvn?: string | null;
};

/**
 * NINBVNVerificationResponse
 */
export type NinbvnVerificationResponse = {
  /**
   * Nin Verified
   */
  nin_verified?: boolean;
  /**
   * Bvn Verified
   */
  bvn_verified?: boolean;
  /**
   * Verification Data
   */
  verification_data?: {
    [key: string]: unknown;
  } | null;
  /**
   * Message
   */
  message: string;
};

/**
 * OAuthClientCreate
 */
export type OAuthClientCreate = {
  /**
   * Client Name
   */
  client_name: string;
  /**
   * Client Description
   */
  client_description?: string | null;
  /**
   * Client Uri
   */
  client_uri?: string | null;
  /**
   * Redirect Uris
   */
  redirect_uris: Array<string>;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Grant Types
   */
  grant_types?: Array<string>;
  /**
   * Response Types
   */
  response_types?: Array<string>;
  /**
   * Is Confidential
   */
  is_confidential?: boolean;
};

/**
 * OAuthClientResponse
 */
export type OAuthClientResponse = {
  /**
   * Client Name
   */
  client_name: string;
  /**
   * Client Description
   */
  client_description?: string | null;
  /**
   * Client Uri
   */
  client_uri?: string | null;
  /**
   * Redirect Uris
   */
  redirect_uris: Array<string>;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Id
   */
  id: number;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Client Secret
   */
  client_secret: string;
  /**
   * Grant Types
   */
  grant_types: Array<string>;
  /**
   * Response Types
   */
  response_types: Array<string>;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Is Confidential
   */
  is_confidential: boolean;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type?: string;
  /**
   * Expires In
   */
  expires_in: number;
  /**
   * Refresh Token
   */
  refresh_token?: string | null;
  /**
   * Scope
   */
  scope?: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Phone Number
   */
  phone_number?: string | null;
  /**
   * Password
   */
  password: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserProfile
 */
export type UserProfile = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Phone Number
   */
  phone_number?: string | null;
  /**
   * Is Verified
   */
  is_verified: boolean;
  /**
   * Nin Verified
   */
  nin_verified: boolean;
  /**
   * Bvn Verified
   */
  bvn_verified: boolean;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Phone Number
   */
  phone_number?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Is Verified
   */
  is_verified: boolean;
  /**
   * Nin Verified
   */
  nin_verified: boolean;
  /**
   * Bvn Verified
   */
  bvn_verified: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at?: string | null;
  /**
   * Last Login
   */
  last_login?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OpenidConfigurationWellKnownOpenidConfigurationGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/.well-known/openid_configuration";
};

export type OpenidConfigurationWellKnownOpenidConfigurationGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type JwksWellKnownJwksJsonGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/.well-known/jwks.json";
};

export type JwksWellKnownJwksJsonGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterUserApiV1AuthRegisterPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/v1/auth/register";
};

export type RegisterUserApiV1AuthRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterUserApiV1AuthRegisterPostError =
  RegisterUserApiV1AuthRegisterPostErrors[keyof RegisterUserApiV1AuthRegisterPostErrors];

export type RegisterUserApiV1AuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type RegisterUserApiV1AuthRegisterPostResponse =
  RegisterUserApiV1AuthRegisterPostResponses[keyof RegisterUserApiV1AuthRegisterPostResponses];

export type LoginUserApiV1AuthLoginPostData = {
  body: BodyLoginUserApiV1AuthLoginPost;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login";
};

export type LoginUserApiV1AuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginUserApiV1AuthLoginPostError =
  LoginUserApiV1AuthLoginPostErrors[keyof LoginUserApiV1AuthLoginPostErrors];

export type LoginUserApiV1AuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type LoginUserApiV1AuthLoginPostResponse =
  LoginUserApiV1AuthLoginPostResponses[keyof LoginUserApiV1AuthLoginPostResponses];

export type LoginUserJsonApiV1AuthLoginJsonPostData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login/json";
};

export type LoginUserJsonApiV1AuthLoginJsonPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginUserJsonApiV1AuthLoginJsonPostError =
  LoginUserJsonApiV1AuthLoginJsonPostErrors[keyof LoginUserJsonApiV1AuthLoginJsonPostErrors];

export type LoginUserJsonApiV1AuthLoginJsonPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type LoginUserJsonApiV1AuthLoginJsonPostResponse =
  LoginUserJsonApiV1AuthLoginJsonPostResponses[keyof LoginUserJsonApiV1AuthLoginJsonPostResponses];

export type GetUserInfoApiV1AuthUserinfoGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/userinfo";
};

export type GetUserInfoApiV1AuthUserinfoGetResponses = {
  /**
   * Successful Response
   */
  200: UserProfile;
};

export type GetUserInfoApiV1AuthUserinfoGetResponse =
  GetUserInfoApiV1AuthUserinfoGetResponses[keyof GetUserInfoApiV1AuthUserinfoGetResponses];

export type ReadUserMeApiV1AuthMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type ReadUserMeApiV1AuthMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type ReadUserMeApiV1AuthMeGetResponse =
  ReadUserMeApiV1AuthMeGetResponses[keyof ReadUserMeApiV1AuthMeGetResponses];

export type CreateOauthClientApiV1Oauth2ClientsPostData = {
  body: OAuthClientCreate;
  path?: never;
  query?: never;
  url: "/api/v1/oauth2/clients";
};

export type CreateOauthClientApiV1Oauth2ClientsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOauthClientApiV1Oauth2ClientsPostError =
  CreateOauthClientApiV1Oauth2ClientsPostErrors[keyof CreateOauthClientApiV1Oauth2ClientsPostErrors];

export type CreateOauthClientApiV1Oauth2ClientsPostResponses = {
  /**
   * Successful Response
   */
  200: OAuthClientResponse;
};

export type CreateOauthClientApiV1Oauth2ClientsPostResponse =
  CreateOauthClientApiV1Oauth2ClientsPostResponses[keyof CreateOauthClientApiV1Oauth2ClientsPostResponses];

export type GetOauthClientApiV1Oauth2ClientsClientIdGetData = {
  body?: never;
  path: {
    /**
     * Client Id
     */
    client_id: string;
  };
  query?: never;
  url: "/api/v1/oauth2/clients/{client_id}";
};

export type GetOauthClientApiV1Oauth2ClientsClientIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOauthClientApiV1Oauth2ClientsClientIdGetError =
  GetOauthClientApiV1Oauth2ClientsClientIdGetErrors[keyof GetOauthClientApiV1Oauth2ClientsClientIdGetErrors];

export type GetOauthClientApiV1Oauth2ClientsClientIdGetResponses = {
  /**
   * Successful Response
   */
  200: OAuthClientResponse;
};

export type GetOauthClientApiV1Oauth2ClientsClientIdGetResponse =
  GetOauthClientApiV1Oauth2ClientsClientIdGetResponses[keyof GetOauthClientApiV1Oauth2ClientsClientIdGetResponses];

export type AuthorizeApiV1Oauth2AuthorizeGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Response Type
     */
    response_type: string;
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Redirect Uri
     */
    redirect_uri: string;
    /**
     * Scope
     */
    scope?: string | null;
    /**
     * State
     */
    state?: string | null;
  };
  url: "/api/v1/oauth2/authorize";
};

export type AuthorizeApiV1Oauth2AuthorizeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthorizeApiV1Oauth2AuthorizeGetError =
  AuthorizeApiV1Oauth2AuthorizeGetErrors[keyof AuthorizeApiV1Oauth2AuthorizeGetErrors];

export type AuthorizeApiV1Oauth2AuthorizeGetResponses = {
  /**
   * Response Authorize Api V1 Oauth2 Authorize Get
   * Successful Response
   */
  200: unknown;
};

export type GetTokenApiV1Oauth2TokenPostData = {
  body: BodyGetTokenApiV1Oauth2TokenPost;
  path?: never;
  query?: never;
  url: "/api/v1/oauth2/token";
};

export type GetTokenApiV1Oauth2TokenPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTokenApiV1Oauth2TokenPostError =
  GetTokenApiV1Oauth2TokenPostErrors[keyof GetTokenApiV1Oauth2TokenPostErrors];

export type GetTokenApiV1Oauth2TokenPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type GetTokenApiV1Oauth2TokenPostResponse =
  GetTokenApiV1Oauth2TokenPostResponses[keyof GetTokenApiV1Oauth2TokenPostResponses];

export type VerifyNinBvnApiV1IdentityVerifyNinBvnPostData = {
  body: NinbvnVerificationRequest;
  path?: never;
  query?: never;
  url: "/api/v1/identity/verify-nin-bvn";
};

export type VerifyNinBvnApiV1IdentityVerifyNinBvnPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyNinBvnApiV1IdentityVerifyNinBvnPostError =
  VerifyNinBvnApiV1IdentityVerifyNinBvnPostErrors[keyof VerifyNinBvnApiV1IdentityVerifyNinBvnPostErrors];

export type VerifyNinBvnApiV1IdentityVerifyNinBvnPostResponses = {
  /**
   * Successful Response
   */
  200: NinbvnVerificationResponse;
};

export type VerifyNinBvnApiV1IdentityVerifyNinBvnPostResponse =
  VerifyNinBvnApiV1IdentityVerifyNinBvnPostResponses[keyof VerifyNinBvnApiV1IdentityVerifyNinBvnPostResponses];

export type GetVerificationStatusApiV1IdentityVerificationStatusGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/identity/verification-status";
};

export type GetVerificationStatusApiV1IdentityVerificationStatusGetResponses = {
  /**
   * Response Get Verification Status Api V1 Identity Verification Status Get
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetVerificationStatusApiV1IdentityVerificationStatusGetResponse =
  GetVerificationStatusApiV1IdentityVerificationStatusGetResponses[keyof GetVerificationStatusApiV1IdentityVerificationStatusGetResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};
