// This file is auto-generated by @hey-api/openapi-ts

/**
 * AIAnalyzeRequest
 */
export type AiAnalyzeRequest = {
  /**
   * Text
   */
  text: string;
  /**
   * Analysis Type
   */
  analysis_type?: string | null;
};

/**
 * AIChatRequest
 */
export type AiChatRequest = {
  /**
   * Message
   */
  message: string;
  /**
   * Conversation Id
   */
  conversation_id?: string | null;
  /**
   * Context
   */
  context?: string | null;
};

/**
 * AIGenerateRequest
 */
export type AiGenerateRequest = {
  /**
   * Prompt
   */
  prompt: string;
  /**
   * Max Tokens
   */
  max_tokens?: number | null;
  /**
   * Temperature
   */
  temperature?: number | null;
};

/**
 * AITranslateRequest
 */
export type AiTranslateRequest = {
  /**
   * Text
   */
  text: string;
  /**
   * Source Language
   */
  source_language?: string | null;
  /**
   * Target Language
   */
  target_language: string;
};

/**
 * BVNLookupRequest
 */
export type BvnLookupRequest = {
  /**
   * Bvn
   */
  bvn: string;
};

/**
 * BVNMatchRequest
 */
export type BvnMatchRequest = {
  /**
   * Bvn
   */
  bvn: string;
  /**
   * First Name
   */
  first_name: string;
  /**
   * Last Name
   */
  last_name: string;
  /**
   * Date Of Birth
   */
  date_of_birth?: string | null;
};

/**
 * BVNVerifyRequest
 */
export type BvnVerifyRequest = {
  /**
   * Bvn
   */
  bvn: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: ValidationError[];
};

/**
 * NINLookupRequest
 */
export type NinLookupRequest = {
  /**
   * Nin
   */
  nin: string;
};

/**
 * NINVerifyRequest
 */
export type NinVerifyRequest = {
  /**
   * Nin
   */
  nin: string;
};

/**
 * OAuth2ClientCreate
 */
export type OAuth2ClientCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Redirect Uris
   */
  redirect_uris?: string[];
};

/**
 * OAuth2TokenRequest
 */
export type OAuth2TokenRequest = {
  /**
   * Grant Type
   */
  grant_type: string;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Client Secret
   */
  client_secret?: string | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * Password
   */
  password?: string | null;
};

/**
 * OTPGenerateRequest
 */
export type OtpGenerateRequest = {
  /**
   * Phone Number
   */
  phone_number: string;
  /**
   * Length
   */
  length?: number | null;
  /**
   * Expiry Minutes
   */
  expiry_minutes?: number | null;
};

/**
 * OTPVerifyRequest
 */
export type OtpVerifyRequest = {
  /**
   * Phone Number
   */
  phone_number: string;
  /**
   * Otp Code
   */
  otp_code: string;
};

/**
 * PasswordReset
 */
export type PasswordReset = {
  /**
   * New Password
   */
  new_password: string;
};

/**
 * SMSBulkRequest
 */
export type SmsBulkRequest = {
  /**
   * Recipients
   */
  recipients: string[];
  /**
   * Message
   */
  message: string;
  /**
   * Sender Id
   */
  sender_id?: string | null;
};

/**
 * SMSSendRequest
 */
export type SmsSendRequest = {
  /**
   * To
   */
  to: string;
  /**
   * Message
   */
  message: string;
  /**
   * Sender Id
   */
  sender_id?: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Password
   */
  password: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
  /**
   * Identifier
   */
  identifier: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Username
   */
  username?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: (string | number)[];
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type ApiGetHealthHealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type ApiGetHealthHealthCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ApiGetMetricsMetricsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/metrics";
};

export type ApiGetMetricsMetricsResponses = {
  /**
   * Successful Response
   */
  200: string;
};

export type ApiGetMetricsMetricsResponse =
  ApiGetMetricsMetricsResponses[keyof ApiGetMetricsMetricsResponses];

export type ApiGetRootRootData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type ApiGetRootRootResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthPostApiV1AuthLoginLoginData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login";
};

export type AuthPostApiV1AuthLoginLoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthPostApiV1AuthLoginLoginError =
  AuthPostApiV1AuthLoginLoginErrors[keyof AuthPostApiV1AuthLoginLoginErrors];

export type AuthPostApiV1AuthLoginLoginResponses = {
  /**
   * Response Auth Post Api V1 Auth Login Login
   * Successful Response
   */
  200: unknown;
};

export type AuthPostApiV1AuthLoginJsonLoginJsonData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login/json";
};

export type AuthPostApiV1AuthLoginJsonLoginJsonErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthPostApiV1AuthLoginJsonLoginJsonError =
  AuthPostApiV1AuthLoginJsonLoginJsonErrors[keyof AuthPostApiV1AuthLoginJsonLoginJsonErrors];

export type AuthPostApiV1AuthLoginJsonLoginJsonResponses = {
  /**
   * Response Auth Post Api V1 Auth Login Json Login Json
   * Successful Response
   */
  200: unknown;
};

export type AuthGetApiV1AuthMeGetCurrentUserProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type AuthGetApiV1AuthMeGetCurrentUserProfileResponses = {
  /**
   * Response Auth Get Api V1 Auth Me Get Current User Profile
   * Successful Response
   */
  200: unknown;
};

export type AuthPostApiV1AuthLogoutLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/logout";
};

export type AuthPostApiV1AuthLogoutLogoutResponses = {
  /**
   * Response Auth Post Api V1 Auth Logout Logout
   * Successful Response
   */
  200: unknown;
};

export type AuthPostApiV1AuthTokenOauthTokenData = {
  body: OAuth2TokenRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/token";
};

export type AuthPostApiV1AuthTokenOauthTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthPostApiV1AuthTokenOauthTokenError =
  AuthPostApiV1AuthTokenOauthTokenErrors[keyof AuthPostApiV1AuthTokenOauthTokenErrors];

export type AuthPostApiV1AuthTokenOauthTokenResponses = {
  /**
   * Response Auth Post Api V1 Auth Token Oauth Token
   * Successful Response
   */
  200: unknown;
};

export type AuthGetApiV1AuthAdminUsersListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/admin/users";
};

export type AuthGetApiV1AuthAdminUsersListUsersResponses = {
  /**
   * Response Auth Get Api V1 Auth Admin Users List Users
   * Successful Response
   */
  200: unknown;
};

export type AuthPostApiV1AuthAdminUsersCreateUserData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/v1/auth/admin/users";
};

export type AuthPostApiV1AuthAdminUsersCreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthPostApiV1AuthAdminUsersCreateUserError =
  AuthPostApiV1AuthAdminUsersCreateUserErrors[keyof AuthPostApiV1AuthAdminUsersCreateUserErrors];

export type AuthPostApiV1AuthAdminUsersCreateUserResponses = {
  /**
   * Response Auth Post Api V1 Auth Admin Users Create User
   * Successful Response
   */
  200: unknown;
};

export type AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/v1/auth/admin/users/{user_id}";
};

export type AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserError =
  AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserErrors[keyof AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserErrors];

export type AuthDeleteApiV1AuthAdminUsersUserIdDeleteUserResponses = {
  /**
   * Response Auth Delete Api V1 Auth Admin Users User Id Delete User
   * Successful Response
   */
  200: unknown;
};

export type AuthGetApiV1AuthAdminUsersUserIdGetUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/v1/auth/admin/users/{user_id}";
};

export type AuthGetApiV1AuthAdminUsersUserIdGetUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthGetApiV1AuthAdminUsersUserIdGetUserError =
  AuthGetApiV1AuthAdminUsersUserIdGetUserErrors[keyof AuthGetApiV1AuthAdminUsersUserIdGetUserErrors];

export type AuthGetApiV1AuthAdminUsersUserIdGetUserResponses = {
  /**
   * Response Auth Get Api V1 Auth Admin Users User Id Get User
   * Successful Response
   */
  200: unknown;
};

export type AuthPutApiV1AuthAdminUsersUserIdUpdateUserData = {
  body: UserUpdate;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/v1/auth/admin/users/{user_id}";
};

export type AuthPutApiV1AuthAdminUsersUserIdUpdateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthPutApiV1AuthAdminUsersUserIdUpdateUserError =
  AuthPutApiV1AuthAdminUsersUserIdUpdateUserErrors[keyof AuthPutApiV1AuthAdminUsersUserIdUpdateUserErrors];

export type AuthPutApiV1AuthAdminUsersUserIdUpdateUserResponses = {
  /**
   * Response Auth Put Api V1 Auth Admin Users User Id Update User
   * Successful Response
   */
  200: unknown;
};

export type AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/v1/auth/admin/users/{user_id}/activate";
};

export type AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserError =
  AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserErrors[keyof AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserErrors];

export type AuthPostApiV1AuthAdminUsersUserIdActivateActivateUserResponses = {
  /**
   * Response Auth Post Api V1 Auth Admin Users User Id Activate Activate User
   * Successful Response
   */
  200: unknown;
};

export type AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/v1/auth/admin/users/{user_id}/deactivate";
};

export type AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserError =
  AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserErrors[keyof AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserErrors];

export type AuthPostApiV1AuthAdminUsersUserIdDeactivateDeactivateUserResponses =
  {
    /**
     * Response Auth Post Api V1 Auth Admin Users User Id Deactivate Deactivate User
     * Successful Response
     */
    200: unknown;
  };

export type AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordData =
  {
    body: PasswordReset;
    path: {
      /**
       * User Id
       */
      user_id: number;
    };
    query?: never;
    url: "/api/v1/auth/admin/users/{user_id}/reset-password";
  };

export type AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordError =
  AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordErrors[keyof AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordErrors];

export type AuthPostApiV1AuthAdminUsersUserIdResetPasswordResetUserPasswordResponses =
  {
    /**
     * Response Auth Post Api V1 Auth Admin Users User Id Reset Password Reset User Password
     * Successful Response
     */
    200: unknown;
  };

export type AuthPostApiV1AuthOauth2ClientsCreateOauthClientData = {
  body: OAuth2ClientCreate;
  path?: never;
  query?: never;
  url: "/api/v1/auth/oauth2/clients";
};

export type AuthPostApiV1AuthOauth2ClientsCreateOauthClientErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthPostApiV1AuthOauth2ClientsCreateOauthClientError =
  AuthPostApiV1AuthOauth2ClientsCreateOauthClientErrors[keyof AuthPostApiV1AuthOauth2ClientsCreateOauthClientErrors];

export type AuthPostApiV1AuthOauth2ClientsCreateOauthClientResponses = {
  /**
   * Response Auth Post Api V1 Auth Oauth2 Clients Create Oauth Client
   * Successful Response
   */
  200: unknown;
};

export type AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientData = {
  body?: never;
  path: {
    /**
     * Client Id
     */
    client_id: string;
  };
  query?: never;
  url: "/api/v1/auth/oauth2/clients/{client_id}";
};

export type AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientError =
  AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientErrors[keyof AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientErrors];

export type AuthGetApiV1AuthOauth2ClientsClientIdGetOauthClientResponses = {
  /**
   * Response Auth Get Api V1 Auth Oauth2 Clients Client Id Get Oauth Client
   * Successful Response
   */
  200: unknown;
};

export type AuthGetApiV1AuthOauth2AuthorizeOauthAuthorizeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/oauth2/authorize";
};

export type AuthGetApiV1AuthOauth2AuthorizeOauthAuthorizeResponses = {
  /**
   * Response Auth Get Api V1 Auth Oauth2 Authorize Oauth Authorize
   * Successful Response
   */
  200: unknown;
};

export type NinPostApiV1NinVerifyVerifyNinData = {
  body: NinVerifyRequest;
  path?: never;
  query?: never;
  url: "/api/v1/nin/verify";
};

export type NinPostApiV1NinVerifyVerifyNinErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type NinPostApiV1NinVerifyVerifyNinError =
  NinPostApiV1NinVerifyVerifyNinErrors[keyof NinPostApiV1NinVerifyVerifyNinErrors];

export type NinPostApiV1NinVerifyVerifyNinResponses = {
  /**
   * Response Nin Post Api V1 Nin Verify Verify Nin
   * Successful Response
   */
  200: unknown;
};

export type NinGetApiV1NinStatusNinGetNinStatusData = {
  body?: never;
  path: {
    /**
     * Nin
     */
    nin: string;
  };
  query?: never;
  url: "/api/v1/nin/status/{nin}";
};

export type NinGetApiV1NinStatusNinGetNinStatusErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type NinGetApiV1NinStatusNinGetNinStatusError =
  NinGetApiV1NinStatusNinGetNinStatusErrors[keyof NinGetApiV1NinStatusNinGetNinStatusErrors];

export type NinGetApiV1NinStatusNinGetNinStatusResponses = {
  /**
   * Response Nin Get Api V1 Nin Status Nin Get Nin Status
   * Successful Response
   */
  200: unknown;
};

export type NinPostApiV1NinLookupLookupNinData = {
  body: NinLookupRequest;
  path?: never;
  query?: never;
  url: "/api/v1/nin/lookup";
};

export type NinPostApiV1NinLookupLookupNinErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type NinPostApiV1NinLookupLookupNinError =
  NinPostApiV1NinLookupLookupNinErrors[keyof NinPostApiV1NinLookupLookupNinErrors];

export type NinPostApiV1NinLookupLookupNinResponses = {
  /**
   * Response Nin Post Api V1 Nin Lookup Lookup Nin
   * Successful Response
   */
  200: unknown;
};

export type BvnPostApiV1BvnVerifyVerifyBvnData = {
  body: BvnVerifyRequest;
  path?: never;
  query?: never;
  url: "/api/v1/bvn/verify";
};

export type BvnPostApiV1BvnVerifyVerifyBvnErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type BvnPostApiV1BvnVerifyVerifyBvnError =
  BvnPostApiV1BvnVerifyVerifyBvnErrors[keyof BvnPostApiV1BvnVerifyVerifyBvnErrors];

export type BvnPostApiV1BvnVerifyVerifyBvnResponses = {
  /**
   * Response Bvn Post Api V1 Bvn Verify Verify Bvn
   * Successful Response
   */
  200: unknown;
};

export type BvnGetApiV1BvnStatusBvnGetBvnStatusData = {
  body?: never;
  path: {
    /**
     * Bvn
     */
    bvn: string;
  };
  query?: never;
  url: "/api/v1/bvn/status/{bvn}";
};

export type BvnGetApiV1BvnStatusBvnGetBvnStatusErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type BvnGetApiV1BvnStatusBvnGetBvnStatusError =
  BvnGetApiV1BvnStatusBvnGetBvnStatusErrors[keyof BvnGetApiV1BvnStatusBvnGetBvnStatusErrors];

export type BvnGetApiV1BvnStatusBvnGetBvnStatusResponses = {
  /**
   * Response Bvn Get Api V1 Bvn Status Bvn Get Bvn Status
   * Successful Response
   */
  200: unknown;
};

export type BvnPostApiV1BvnLookupLookupBvnData = {
  body: BvnLookupRequest;
  path?: never;
  query?: never;
  url: "/api/v1/bvn/lookup";
};

export type BvnPostApiV1BvnLookupLookupBvnErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type BvnPostApiV1BvnLookupLookupBvnError =
  BvnPostApiV1BvnLookupLookupBvnErrors[keyof BvnPostApiV1BvnLookupLookupBvnErrors];

export type BvnPostApiV1BvnLookupLookupBvnResponses = {
  /**
   * Response Bvn Post Api V1 Bvn Lookup Lookup Bvn
   * Successful Response
   */
  200: unknown;
};

export type BvnPostApiV1BvnMatchMatchBvnData = {
  body: BvnMatchRequest;
  path?: never;
  query?: never;
  url: "/api/v1/bvn/match";
};

export type BvnPostApiV1BvnMatchMatchBvnErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type BvnPostApiV1BvnMatchMatchBvnError =
  BvnPostApiV1BvnMatchMatchBvnErrors[keyof BvnPostApiV1BvnMatchMatchBvnErrors];

export type BvnPostApiV1BvnMatchMatchBvnResponses = {
  /**
   * Response Bvn Post Api V1 Bvn Match Match Bvn
   * Successful Response
   */
  200: unknown;
};

export type BvnGetApiV1BvnBanksGetSupportedBanksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/bvn/banks";
};

export type BvnGetApiV1BvnBanksGetSupportedBanksResponses = {
  /**
   * Response Bvn Get Api V1 Bvn Banks Get Supported Banks
   * Successful Response
   */
  200: unknown;
};

export type SmsPostApiV1SmsSendSendSmsData = {
  body: SmsSendRequest;
  path?: never;
  query?: never;
  url: "/api/v1/sms/send";
};

export type SmsPostApiV1SmsSendSendSmsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SmsPostApiV1SmsSendSendSmsError =
  SmsPostApiV1SmsSendSendSmsErrors[keyof SmsPostApiV1SmsSendSendSmsErrors];

export type SmsPostApiV1SmsSendSendSmsResponses = {
  /**
   * Response Sms Post Api V1 Sms Send Send Sms
   * Successful Response
   */
  200: unknown;
};

export type SmsPostApiV1SmsBulkSendBulkSmsData = {
  body: SmsBulkRequest;
  path?: never;
  query?: never;
  url: "/api/v1/sms/bulk";
};

export type SmsPostApiV1SmsBulkSendBulkSmsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SmsPostApiV1SmsBulkSendBulkSmsError =
  SmsPostApiV1SmsBulkSendBulkSmsErrors[keyof SmsPostApiV1SmsBulkSendBulkSmsErrors];

export type SmsPostApiV1SmsBulkSendBulkSmsResponses = {
  /**
   * Response Sms Post Api V1 Sms Bulk Send Bulk Sms
   * Successful Response
   */
  200: unknown;
};

export type SmsPostApiV1SmsOtpGenerateGenerateOtpData = {
  body: OtpGenerateRequest;
  path?: never;
  query?: never;
  url: "/api/v1/sms/otp/generate";
};

export type SmsPostApiV1SmsOtpGenerateGenerateOtpErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SmsPostApiV1SmsOtpGenerateGenerateOtpError =
  SmsPostApiV1SmsOtpGenerateGenerateOtpErrors[keyof SmsPostApiV1SmsOtpGenerateGenerateOtpErrors];

export type SmsPostApiV1SmsOtpGenerateGenerateOtpResponses = {
  /**
   * Response Sms Post Api V1 Sms Otp Generate Generate Otp
   * Successful Response
   */
  200: unknown;
};

export type SmsPostApiV1SmsOtpVerifyVerifyOtpData = {
  body: OtpVerifyRequest;
  path?: never;
  query?: never;
  url: "/api/v1/sms/otp/verify";
};

export type SmsPostApiV1SmsOtpVerifyVerifyOtpErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SmsPostApiV1SmsOtpVerifyVerifyOtpError =
  SmsPostApiV1SmsOtpVerifyVerifyOtpErrors[keyof SmsPostApiV1SmsOtpVerifyVerifyOtpErrors];

export type SmsPostApiV1SmsOtpVerifyVerifyOtpResponses = {
  /**
   * Response Sms Post Api V1 Sms Otp Verify Verify Otp
   * Successful Response
   */
  200: unknown;
};

export type SmsGetApiV1SmsStatusMessageIdGetMessageStatusData = {
  body?: never;
  path: {
    /**
     * Message Id
     */
    message_id: string;
  };
  query?: never;
  url: "/api/v1/sms/status/{message_id}";
};

export type SmsGetApiV1SmsStatusMessageIdGetMessageStatusErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SmsGetApiV1SmsStatusMessageIdGetMessageStatusError =
  SmsGetApiV1SmsStatusMessageIdGetMessageStatusErrors[keyof SmsGetApiV1SmsStatusMessageIdGetMessageStatusErrors];

export type SmsGetApiV1SmsStatusMessageIdGetMessageStatusResponses = {
  /**
   * Response Sms Get Api V1 Sms Status Message Id Get Message Status
   * Successful Response
   */
  200: unknown;
};

export type SmsGetApiV1SmsBalanceGetSmsBalanceData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/sms/balance";
};

export type SmsGetApiV1SmsBalanceGetSmsBalanceResponses = {
  /**
   * Response Sms Get Api V1 Sms Balance Get Sms Balance
   * Successful Response
   */
  200: unknown;
};

export type SmsGetApiV1SmsTemplatesGetMessageTemplatesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/sms/templates";
};

export type SmsGetApiV1SmsTemplatesGetMessageTemplatesResponses = {
  /**
   * Response Sms Get Api V1 Sms Templates Get Message Templates
   * Successful Response
   */
  200: unknown;
};

export type AiPostApiV1AiChatChatCompletionData = {
  body: AiChatRequest;
  path?: never;
  query?: never;
  url: "/api/v1/ai/chat";
};

export type AiPostApiV1AiChatChatCompletionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AiPostApiV1AiChatChatCompletionError =
  AiPostApiV1AiChatChatCompletionErrors[keyof AiPostApiV1AiChatChatCompletionErrors];

export type AiPostApiV1AiChatChatCompletionResponses = {
  /**
   * Response Ai Post Api V1 Ai Chat Chat Completion
   * Successful Response
   */
  200: unknown;
};

export type AiPostApiV1AiGenerateGenerateContentData = {
  body: AiGenerateRequest;
  path?: never;
  query?: never;
  url: "/api/v1/ai/generate";
};

export type AiPostApiV1AiGenerateGenerateContentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AiPostApiV1AiGenerateGenerateContentError =
  AiPostApiV1AiGenerateGenerateContentErrors[keyof AiPostApiV1AiGenerateGenerateContentErrors];

export type AiPostApiV1AiGenerateGenerateContentResponses = {
  /**
   * Response Ai Post Api V1 Ai Generate Generate Content
   * Successful Response
   */
  200: unknown;
};

export type AiPostApiV1AiAnalyzeAnalyzeTextData = {
  body: AiAnalyzeRequest;
  path?: never;
  query?: never;
  url: "/api/v1/ai/analyze";
};

export type AiPostApiV1AiAnalyzeAnalyzeTextErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AiPostApiV1AiAnalyzeAnalyzeTextError =
  AiPostApiV1AiAnalyzeAnalyzeTextErrors[keyof AiPostApiV1AiAnalyzeAnalyzeTextErrors];

export type AiPostApiV1AiAnalyzeAnalyzeTextResponses = {
  /**
   * Response Ai Post Api V1 Ai Analyze Analyze Text
   * Successful Response
   */
  200: unknown;
};

export type AiPostApiV1AiTranslateTranslateTextData = {
  body: AiTranslateRequest;
  path?: never;
  query?: never;
  url: "/api/v1/ai/translate";
};

export type AiPostApiV1AiTranslateTranslateTextErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AiPostApiV1AiTranslateTranslateTextError =
  AiPostApiV1AiTranslateTranslateTextErrors[keyof AiPostApiV1AiTranslateTranslateTextErrors];

export type AiPostApiV1AiTranslateTranslateTextResponses = {
  /**
   * Response Ai Post Api V1 Ai Translate Translate Text
   * Successful Response
   */
  200: unknown;
};

export type AiGetApiV1AiModelsGetAvailableModelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/ai/models";
};

export type AiGetApiV1AiModelsGetAvailableModelsResponses = {
  /**
   * Response Ai Get Api V1 Ai Models Get Available Models
   * Successful Response
   */
  200: unknown;
};

export type AiGetApiV1AiConversationsConversationIdGetConversationData = {
  body?: never;
  path: {
    /**
     * Conversation Id
     */
    conversation_id: string;
  };
  query?: never;
  url: "/api/v1/ai/conversations/{conversation_id}";
};

export type AiGetApiV1AiConversationsConversationIdGetConversationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AiGetApiV1AiConversationsConversationIdGetConversationError =
  AiGetApiV1AiConversationsConversationIdGetConversationErrors[keyof AiGetApiV1AiConversationsConversationIdGetConversationErrors];

export type AiGetApiV1AiConversationsConversationIdGetConversationResponses = {
  /**
   * Response Ai Get Api V1 Ai Conversations Conversation Id Get Conversation
   * Successful Response
   */
  200: unknown;
};

export type AiGetApiV1AiUsageGetUsageStatisticsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/ai/usage";
};

export type AiGetApiV1AiUsageGetUsageStatisticsResponses = {
  /**
   * Response Ai Get Api V1 Ai Usage Get Usage Statistics
   * Successful Response
   */
  200: unknown;
};

export type HealthGetApiV1ServicesHealthGetServicesHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/services/health";
};

export type HealthGetApiV1ServicesHealthGetServicesHealthResponses = {
  /**
   * Response Health Get Api V1 Services Health Get Services Health
   * Successful Response
   */
  200: unknown;
};

export type HealthGetApiV1DpiHealthGetDpiHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/dpi/health";
};

export type HealthGetApiV1DpiHealthGetDpiHealthResponses = {
  /**
   * Response Health Get Api V1 Dpi Health Get Dpi Health
   * Successful Response
   */
  200: unknown;
};

export type HealthGetApiV1ServicesServiceNameHealthGetServiceHealthData = {
  body?: never;
  path: {
    /**
     * Service Name
     */
    service_name: string;
  };
  query?: never;
  url: "/api/v1/services/{service_name}/health";
};

export type HealthGetApiV1ServicesServiceNameHealthGetServiceHealthErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type HealthGetApiV1ServicesServiceNameHealthGetServiceHealthError =
  HealthGetApiV1ServicesServiceNameHealthGetServiceHealthErrors[keyof HealthGetApiV1ServicesServiceNameHealthGetServiceHealthErrors];

export type HealthGetApiV1ServicesServiceNameHealthGetServiceHealthResponses = {
  /**
   * Response Health Get Api V1 Services Service Name Health Get Service Health
   * Successful Response
   */
  200: unknown;
};

export type HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsData = {
  body?: never;
  path: {
    /**
     * Service Name
     */
    service_name: string;
  };
  query?: never;
  url: "/api/v1/services/{service_name}/metrics";
};

export type HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsError =
  HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsErrors[keyof HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsErrors];

export type HealthGetApiV1ServicesServiceNameMetricsGetServiceMetricsResponses =
  {
    /**
     * Response Health Get Api V1 Services Service Name Metrics Get Service Metrics
     * Successful Response
     */
    200: unknown;
  };

export type ExamplesGetApiV1ExamplesNinNinExamplesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/examples/nin";
};

export type ExamplesGetApiV1ExamplesNinNinExamplesResponses = {
  /**
   * Response Examples Get Api V1 Examples Nin Nin Examples
   * Successful Response
   */
  200: unknown;
};

export type ExamplesGetApiV1ExamplesSmsSmsExamplesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/examples/sms";
};

export type ExamplesGetApiV1ExamplesSmsSmsExamplesResponses = {
  /**
   * Response Examples Get Api V1 Examples Sms Sms Examples
   * Successful Response
   */
  200: unknown;
};

export type ExamplesGetApiV1ExamplesAuthAuthExamplesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/examples/auth";
};

export type ExamplesGetApiV1ExamplesAuthAuthExamplesResponses = {
  /**
   * Response Examples Get Api V1 Examples Auth Auth Examples
   * Successful Response
   */
  200: unknown;
};

export type ExamplesGetApiV1ExamplesIntegrationIntegrationExamplesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/examples/integration";
};

export type ExamplesGetApiV1ExamplesIntegrationIntegrationExamplesResponses = {
  /**
   * Response Examples Get Api V1 Examples Integration Integration Examples
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};
